version: "2.2"
services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - $PWD/nginx.conf:/etc/nginx/conf.d/default.conf
      - $PWD:/etc/nginx/certs
    links:
      - app
    restart: always
  app:
    container_name: app
    restart: always
    build: ./
    ports:
      - "8080"
    volumes:
      - "$PWD:/vapor"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ../data/db:/data/db
    ports:
      - "27017"
